# Generated by Django 5.1.1 on 2024-10-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_equipo_cliente'),
        ('energiaplantas', '0004_marcacontrolador_uso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('observaciones', models.CharField(blank=True)),
                ('Horometro', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('Potencia', models.FloatField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('marcacontrolador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energiaplantas.marcacontrolador')),
                ('marcagenerador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energiaplantas.marcagenerador')),
                ('marcamodulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energiaplantas.marcamodulo')),
                ('marcamotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energiaplantas.marcamotor')),
                ('uso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energiaplantas.uso')),
            ],
        ),
    ]
