# Generated by Django 5.1.1 on 2024-10-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energiaplantas', '0006_alter_equipo_cliente_alter_equipo_marcacontrolador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marcacontrolador',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marcagenerador',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marcamodulo',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marcamotor',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uso',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
