# Generated by Django 5.1.1 on 2024-10-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ubicacion',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
