# Generated by Django 5.1.1 on 2024-10-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_ubicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='title',
            new_name='descripcion',
        ),
    ]
