# Generated by Django 5.1.1 on 2024-10-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_rename_title_equipo_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='cliente',
        ),
    ]
