# Generated by Django 5.1.1 on 2024-10-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_equipo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='marcacontrolador',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='marcagenerador',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='marcamodulo',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='marcamotor',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='uso',
        ),
        migrations.DeleteModel(
            name='MarcaControlador',
        ),
        migrations.DeleteModel(
            name='MarcaGenerador',
        ),
        migrations.DeleteModel(
            name='MarcaModulo',
        ),
        migrations.DeleteModel(
            name='MarcaMotor',
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='Uso',
        ),
    ]
