# Generated by Django 5.1.1 on 2024-10-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_remove_cliente_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
